import math

import tensorflow as tf
import tensorflow_probability as tfp
import os 
import numpy as np
import argparse
import json
import agents
import data 
import helpers
from tqdm import tqdm
import pandas as pd


def get_args():
    parser = argparse.ArgumentParser(description="Train PPO on bidirectional multi-step signaling game")

    # environment
    parser.add_argument("--num_same", type=int, default=2, help="defines the number of images observed by both agents")
    parser.add_argument("--num_diff1", type=int, default=2, help="defines the number of images observed by agent 1 only")
    parser.add_argument("--num_diff2", type=int, default=2, help="defines the number of images observed by agent 1 only")
    parser.add_argument("--feature_dim", type=int, default=2048, help="Feature dimension of the input data. Default set to usual imagenet feature dimension; only needs to be adjusted for the dummy data")
    parser.add_argument("--embed_dim", type=int, default=128, help="Embedding dimension of the input data")
    parser.add_argument("--lstm_units", type=int, default=128, help="LSTM units")
    parser.add_argument("--dummy", action="store_true", help="if used, then the agent will be trained on a dummy dataset consisting of onehot vectors")
    parser.add_argument("--trivial", action="store_true", help="Use a single fixed trivial game instance")

    # training
    parser.add_argument("--num_epochs", type=int, default=500, help="number of epochs that the agents train for")
    parser.add_argument("--updates_per_epoch", type=int, default=10)
    parser.add_argument("--num_steps", type=int, default=20, help="maximum number of steps per game")
    parser.add_argument("--num_envs", type=int, default=64, help="number of environments whichs rollouts are collected from in parallel (under the same policy)")
    parser.add_argument("--batch_size", type=int, default=32)
    parser.add_argument("--ppo_buffer_size", type=int, default=10000, help="Buffer size for shuffling the dataset created from the rollouts")
    parser.add_argument("--which_dataset", type=str, default="TRAIN", help="details whether the training (TRAIN), testing (TEST), or validation (VAL) data is used")

    # PPO hyperparameters
    parser.add_argument("--actor_lr", type=float, default=1e-4)
    parser.add_argument("--critic_lr", type=float, default=1e-3)
    parser.add_argument("--clip_epsilon", type=float, default=0.2)
    parser.add_argument("--entropy_coef_img", type=float, default=0.00001)
    parser.add_argument("--entropy_coef_msg", type=float, default=0.00001)

    # Network parameters
    parser.add_argument("--vocab_size", type=int, default=10, help="Size of the discrete communication vocabulary")
    parser.add_argument("--msg_len", type=int, default=3, help="Length of the message generated by the agent")
    parser.add_argument("--which_agent", type=str, default="default", help="details which agent architecture is used; options are 'default' and 'separated' (see agents.py for details)")

    # Misc
    parser.add_argument("--save_every", type=int, default=5, help="Save every nth epoch")
    parser.add_argument("--save", action="store_false", help="create run folder and save results and plots in it")
    parser.add_argument("--ppo_kl_early_stopping_threshold", type=float, default=0.02, help="Early stopping threshold for PPO") #see also https://iclr-blog-track.github.io/2022/03/25/ppo-implementation-details/
    return parser.parse_args()




def load_config(config_path):
    """Load a saved config.json and return an argparse.Namespace compatible with your training code.
    Args:
        config_path(str): path to directory where the configuration file (copnfig.json) is saved
    Return:
        argparse.Namespace with the values from config.json loaded into
    """
    # Start from default args (ensures new args get defaults)
    args = get_args()

    with open(config_path, "r") as f:
        saved = json.load(f)

    for k, v in saved.items():
        if hasattr(args, k):
            setattr(args, k, v)
        else:
            print(f"[load_config] Warning: unknown arg '{k}' in config")

    return args

def get_agent_class_from_desc(desc):
    agent_dict = {'default': agents.AgentActor,
                  'separated': agents.AgentActorSeparated
                  }
    a_class = agent_dict[desc]
    return a_class

def initialize_agents(actor_lr, critic_lr, feature_dim, embed_dim, lstm_units, vocab_size, msg_len, which_agent):
    """"Initialises agent actor and critic networks
    Args:
        actor_lr, critic_lr (float): Learning rates per network passed to the optimizer
        feature_dim (int): Feature dimension of the input data 
        vocab_size (int): Size of the discrete communication vocabulary
        msg_len (int): Length of the message generated by the agent
    
    Returns: Instances of th actor (agent) and critic networks, as well as their respective optimizers
        """
    agent_class = get_agent_class_from_desc(which_agent)
    agent = agent_class(vocab_size=vocab_size, msg_len=msg_len, embed_dim=embed_dim, lstm_units=lstm_units)
    critic = agents.AgentCritic(vocab_size=vocab_size, embed_dim=embed_dim, lstm_units=lstm_units)

    optimizer_agent = tf.keras.optimizers.Adam(actor_lr) 
    optimizer_crit = tf.keras.optimizers.Adam(critic_lr) 

    # not inherently tied to the dummy data, just a dry run to create the necessary channels
    dummy_features = tf.zeros([1, 10, feature_dim])  
    dummy_msg = tf.zeros([1, agent.msg_len], dtype=tf.int32)

    dummy_h = tf.zeros([1, agent.lstm.units])
    dummy_c = tf.zeros([1, agent.lstm.units])

    agent(dummy_features, dummy_msg, (dummy_h, dummy_c))
    critic(dummy_features, dummy_msg, (dummy_h, dummy_c))

    # explicitly initializing optimizer slots to avoid singleton variable error (due to train_step call with second model)
    helpers.initialize_optimizer_slots(optimizer_agent, agent)
    helpers.initialize_optimizer_slots(optimizer_crit, critic)

    return agent, critic, optimizer_agent, optimizer_crit


def generate_dummy_ppo_dataset(num_same, num_diff1, num_diff2,
                                shuffle_buffer_size, prefetch_buffer_size, batch_size, which, feature_dim):
    """
    Returns batches of one-hot features shaped like [num_same + num_diff1 + num_diff2, feature_dim]
    
    Args:
        num_same (int): Number of objects that are shared between agents
        num_diff1 (int): Number of objects that are only perceived by agent 1
        num_diff2 (int): Number of objects that are only perceived by agent 2
        shuffle_buffer_size (int): Buffer size for shuffling a tf.dataset
        prefetch_buffer_size (int): Buffer size for prefetching elements of a tf.dataset
        batch_size (int): Size of the batch produced
        which (str): String that details whether the train, test, or validation portion of the input dataset is used
        feature_dim (int): length of feature vector

    Returns:
        A tensorflow dataset that contains batched version of the input dataset consisting of 
        ((onehot_dummy_features_agent1, target_vector_agent1),(onehot_dummy_features_agent2, target_vector_agent2)) elements
    
    """
    train, val, test = data.load_dummy_feature_datasets(feature_dim)

    if which.upper() == "TRAIN":
        ds = train
    elif which.upper() == "VAL":
        ds = val
    else:
        ds = test

    game_input_ds = data.create_game_instances_dataset(ds, num_same, num_diff1, num_diff2)

    game_input_ds = game_input_ds.shuffle(shuffle_buffer_size)
    game_input_ds = game_input_ds.batch(batch_size)
    game_input_ds = game_input_ds.prefetch(prefetch_buffer_size) 

    return game_input_ds


def generate_trivial_ppo_dataset(feature_dim=16,batch_size=1):
    """
    Returns a dataset with exactly one fixed game instance,
    repeated indefinitely. It's hard-coded for debugging.
    """

    # Shared target referents (same for both agents) 
    shared = tf.one_hot(3, feature_dim)

    # distractors referents (not shared, unique to each agent) 
    distractor_a1 = tf.one_hot(15, feature_dim)
    distractor_a2 = tf.one_hot(5, feature_dim)

    # combined referents, observable env per agent
    features_a1 = tf.stack([shared, distractor_a1], axis=0)
    features_a2 = tf.stack([shared,distractor_a2], axis=0)

    # target vector showing which image is a target
    targets_a1 = tf.constant([1.0, 0.0])
    targets_a2 = tf.constant([1.0, 0.0])

    #add batch dimension
    features_a1 = features_a1[None, ...]   # [1, 2, feature_dim]
    features_a2 = features_a2[None, ...]
    targets_a1 = targets_a1[None, ...]     # [1, 2]
    targets_a2 = targets_a2[None, ...]

    # turn into tf.dataset
    dataset = tf.data.Dataset.from_tensors(
        ((features_a1, targets_a1),
         (features_a2, targets_a2))
    )

    # repeat forever so PPO never exhausts it
    dataset = dataset.repeat()

    return dataset


def generate_ppo_dataset(num_same, num_diff1, num_diff2, shuffle_buffer_size, prefetch_buffer_size, batch_size, which):
    """generates a dataset that contains tuples of features, target pair per agent

    Args:
        num_same (int): Number of objects that are shared between agents
        num_diff1 (int): Number of objects that are only perceived by agent 1
        num_diff2 (int): Number of objects that are only perceived by agent 2
        shuffle_buffer_size (int): Buffer size for shuffling a tf.dataset
        prefetch_buffer_size (int): Buffer size for prefetching elements of a tf.dataset
        batch_size (int): Size of the batch produced
        which (str): String that details whether the train, test, or validation portion of the input dataset is used

    Returns:
        A tensorflow dataset that contains batched version of the input dataset consisting of 
        ((image_features_agent1, target_vector_agent1),(image_features_agent2, target_vector_agent2)) elements
    """

    if which == 'TRAIN':
        path = os.path.join(os.getcwd(), "saved_data/train")
    elif which == 'TEST':
        path = os.path.join(os.getcwd(), "saved_data/test")
    elif which == 'VAL':
        path = os.path.join(os.getcwd(), "saved_data/val")

    dataset = tf.data.Dataset.load(path)
    game_input_ds = data.create_game_instances_dataset(dataset, num_same, num_diff1, num_diff2)

    game_input_ds = game_input_ds.shuffle(shuffle_buffer_size)
    game_input_ds = game_input_ds.batch(batch_size)
    game_input_ds = game_input_ds.prefetch(prefetch_buffer_size) 

    return game_input_ds


def rollout_step(agent, critic, features, targets, input_message, 
                 prev_state_actor_h, prev_state_actor_c, 
                 prev_state_critic_h, prev_state_critic_c, 
                 reward_function):
    """a function that produces a single rollout step 

    Args:
        agent (tf.keras.Model): A reinforcement learning agent from agents.py
        critic (tf.keras.Model): A reinforcement learning critic from agents.py
        features (tensor): A set of features describing images seen by the agent; shape [batch_size, num_imgs, feature_dim]
        targets (tensor): A binary tensor that details whether a feature tensor is a target (=1) or not (=0); shape [batch_size, num_img]
        input_message (tensor): A tensor of discrete symbols that was sent by the other agent (or an initial message); shape [batch_size, message_length]
        prev_state_actor_h (tensor): previous lstm hidden state from the actor network
        prev_state_actor_c (tensor): previous lstm cell state from the actor network
        prev_state_critic_h (tensor):previous lstm hidden state from the critic network
        prev_state_critic_c (tensor): previous lstm cell state from the critic network
        reward_function (function): some reward function based on correct target prediction 
            - takes predictions and targets as inputs

    Returns:
        A list of dicts containing values collected during each rollout step
            - features: the same features from the input
            - input_messages: message the agent got as input
            - output_messages: message sampled
            - preds: the agents prediction on what images are targets
            - img_logps: log probabilities based on the probability distribution over the images
            - msg_logps: log probabilities based on the probability distribution over the message
            - joint_logps: combined log probability of img_logps and msg_logps
            - rewards: Rewards returned by the reward function based on the correct target prediction
            - values: Critics predicted value based on image and message inputs
            - prev_state_actor_h:  hidden state of the agent's LSTM after this step (used as previous state for the input in the next step)
            - prev_state_actor_c:  cell state of the agent's LSTM after this step (used as previous state for the input in the next step)         
            - prev_state_critic_h: hidden state of the agent's LSTM after this step (used as previous state for the input in the next step)
            - prev_state_critic_c: cell state of the agent's LSTM after this step (used as previous state for the input in the next step)

    """


    probs_img, probs_msg, next_state_actor = agent(features, input_message, (prev_state_actor_h, prev_state_actor_c))
    vals, next_state_critic = critic(features, input_message, (prev_state_critic_h, prev_state_critic_c))

    img_dist = tfp.distributions.Bernoulli(probs=probs_img)
    preds = img_dist.sample() 
    img_logps =img_dist.log_prob(preds)

    msg_dist = tfp.distributions.Categorical(probs=probs_msg) 
    output_messages = msg_dist.sample()
    msg_logps = msg_dist.log_prob(output_messages)

    preds = tf.cast(preds, dtype=tf.float32)

    rewards = reward_function(preds, targets)
    joint_logps = tf.reduce_sum(img_logps, axis=-1) + tf.reduce_sum(msg_logps, axis=-1)
    
    return {
         "features": features,                  # [batch_size, num_imgs, feature_dim]
         "input_messages": input_message,       # [batch_size, msg_len] 
         "output_messages": output_messages,    # [batch_size, msg_len] 
         "targets": targets,
         "preds": preds,                        # [batch_size, num_imgs]
         "img_logps": img_logps,                # [batch_size,]
         "msg_logps": msg_logps,                # [batch_size, num_imgs]
         "joint_logps": joint_logps,            # [batch_size,]
         "rewards": rewards,                    # [batch_size,]
         "values": vals,                        # [batch_size,]
         "prev_state_actor_h": next_state_actor[0],     # [batch_size, lstm_units]
         "prev_state_actor_c": next_state_actor[1],     # [batch_size, lstm_units]
         "prev_state_critic_h": next_state_critic[0],   # [batch_size, lstm_units]
         "prev_state_critic_c": next_state_critic[1],   # [batch_size, lstm_units]
       }


def do_n_rollout_steps(agent, critic, features_a1, targets_a1, 
                        features_a2, targets_a2,
                        reward_function, num_steps):
    """collects num_steps many rollout steps for both agents and merges all into a single dictionary

    Args:
        agent (tf.keras.Model): Reinforcement learning actor network from agents.py
        critic (tf.keras.Model): Reinforcement learning critic network from agents.py
        features_a1, features_a2 (tensor): Sets of features describing images seen by the agents respectively [batch_size, num_img, feature_dim]
        targets_a1, targets_a2 (tensor): Binary tensors that details whether a feature tensor is a target (=1) or not (=0), for each agent respectively; shape [batch_size, num_img]
        reward_function (function): some reward function based on correct target prediction 
            - takes predictions and targets as inputs
        num_steps (int): The number of steps until the rollout collection is terminated
        
    Return:
        A dictionary with fused timesteps of num_step many dictionaries that contain the values of the rollout steps for each agent 
    """
    batch_size = tf.shape(features_a1)[0]

    two_agents_rollout = {
        "agent_1": {key: [] for key in ["features", "input_messages", "output_messages", "targets", "preds", "img_logps", "msg_logps", "joint_logps", "rewards", "joint_rewards", "values", "prev_state_actor_h", "prev_state_actor_c", "prev_state_critic_h", "prev_state_critic_c"]},
        "agent_2": {key: [] for key in ["features", "input_messages", "output_messages", "targets", "preds", "img_logps", "msg_logps", "joint_logps", "rewards", "joint_rewards", "values", "prev_state_actor_h", "prev_state_actor_c", "prev_state_critic_h", "prev_state_critic_c"]},
    }

    for step in range(num_steps):
        
        if step == 0:
            input_message_a1 = tf.zeros([batch_size, agent.msg_len], dtype=tf.int32)   
            input_message_a2 = tf.zeros([batch_size, agent.msg_len], dtype=tf.int32)   
            
            prev_state_actor_h_a1 = tf.zeros([batch_size, agent.lstm.units])
            prev_state_actor_c_a1 = tf.zeros([batch_size, agent.lstm.units])
            prev_state_actor_h_a2 = tf.zeros([batch_size, agent.lstm.units])
            prev_state_actor_c_a2 = tf.zeros([batch_size, agent.lstm.units])

            prev_state_critic_h_a1 = tf.zeros([batch_size, critic.lstm.units])
            prev_state_critic_c_a1 = tf.zeros([batch_size, critic.lstm.units])
            prev_state_critic_h_a2 = tf.zeros([batch_size, critic.lstm.units])
            prev_state_critic_c_a2 = tf.zeros([batch_size, critic.lstm.units])
        else:
            input_message_a1 = two_agents_rollout["agent_2"]["output_messages"][step-1]
            input_message_a2 = two_agents_rollout["agent_1"]["output_messages"][step-1]

            prev_state_actor_h_a1 = two_agents_rollout["agent_1"]["prev_state_actor_h"][step-1]
            prev_state_actor_c_a1 = two_agents_rollout["agent_1"]["prev_state_actor_c"][step-1]
            prev_state_actor_h_a2 = two_agents_rollout["agent_2"]["prev_state_actor_h"][step-1]
            prev_state_actor_c_a2 = two_agents_rollout["agent_2"]["prev_state_actor_c"][step-1]

            prev_state_critic_h_a1 = two_agents_rollout["agent_1"]["prev_state_critic_h"][step-1]
            prev_state_critic_c_a1 = two_agents_rollout["agent_1"]["prev_state_critic_c"][step-1]
            prev_state_critic_h_a2 = two_agents_rollout["agent_2"]["prev_state_critic_h"][step-1]
            prev_state_critic_c_a2 = two_agents_rollout["agent_2"]["prev_state_critic_c"][step-1]


        # rollout step for each agent
        rollout_step_a1 = rollout_step(agent, critic, 
                                       features_a1, targets_a1, 
                                       input_message_a1,
                                       prev_state_actor_h_a1, prev_state_actor_c_a1,
                                       prev_state_critic_h_a1, prev_state_critic_c_a1,
                                       reward_function)
        
        rollout_step_a2 = rollout_step(agent, critic, 
                                       features_a2, targets_a2, 
                                       input_message_a2, 
                                       prev_state_actor_h_a2, prev_state_actor_c_a2,
                                       prev_state_critic_h_a2, prev_state_critic_c_a2,
                                       reward_function)

        # writing the rollout step data into dict
        for k, v in rollout_step_a1.items():
            two_agents_rollout["agent_1"][k].append(v)
        for k, v in rollout_step_a2.items():
            two_agents_rollout["agent_2"][k].append(v)
        
    # concatenating both rollouts into one 
    for agent in ["agent_1", "agent_2"]:
        for k in two_agents_rollout[agent]:
            two_agents_rollout[agent][k] = tf.stack(two_agents_rollout[agent][k], axis=0)

    # getting joint rewards for each rollout step and assigning it to each agent
    two_agents_rollout["agent_1"]["joint_rewards"] = (two_agents_rollout["agent_1"]["rewards"] + two_agents_rollout["agent_2"]["rewards"])/2 
    two_agents_rollout["agent_2"]["joint_rewards"] = (two_agents_rollout["agent_1"]["rewards"] + two_agents_rollout["agent_2"]["rewards"])/2

    return two_agents_rollout

    
def do_k_rollouts(feature_dataset, agent, critic, reward_function, num_steps, k_rollouts):
    """A function that carries out k many separate rollouts
    Args:
        feature_dataset (tf.dataset): consisting of ((image_features_agent1, target_vector_agent1),(image_features_agent2, target_vector_agent2)) elements
        agent (tf.keras.Model): Reinforcement learning actor network from agents.py
        critic (tf.keras.Model): Reinforcement learning critic network from agents.py
        reward_function (function): some reward function based on correct target prediction 
            - takes predictions and targets as inputs
        num_steps (int): The number of steps until the rollout collection is terminated
        k_rollouts (int): number of environments (games) from which rollouts are collected in parallel
    
    Return:
        A list of k rollouts with each element being a dict that contains all rollout information for both agents over num_step timesteps
    """
    agg = []
    for (features_a1, targets_a1), (features_a2, targets_a2) in feature_dataset.take(k_rollouts):

        rollout_steps = do_n_rollout_steps(agent, critic, features_a1, targets_a1,
                                                features_a2, targets_a2,
                                                reward_function, num_steps)
        agg.append(rollout_steps)

    return agg

        

def merge_rollouts(k_rollouts):
    """merges all k*m rollouts along the rollout parameters
    
    Args:
        k_rollouts (list): List of k many rollouts with m minibatches and n rollout steps each
    Return:
        Dictionary that contains the merged rollout information
    """
    merged_rollouts = {
        "agent_1": {},
        "agent_2": {},
    }

    for a in ["agent_1", "agent_2"]:
        for key in k_rollouts[0]["agent_1"].keys():

            tensors = []
            for r in k_rollouts:
                t = r[a][key]
                if tf.rank(t) == 1:
                    t = t[:, None]  # [num_steps] -> [num_steps, 1]
                tensors.append(t)

            merged = tf.concat(tensors, axis=1)
            tf.debugging.assert_rank_at_least(merged, 2)

            # transposing in such a way that batch_size is first and num_steps second
            perm = tf.concat([[1, 0], tf.range(2, tf.rank(merged))], axis=0)
            merged = tf.transpose(merged, perm)
            
            merged_rollouts[a][key] = merged

    return merged_rollouts

def prepare_ppo_information(merged, critic):
    """Calculates and adds addvantage and return information to the merged rollout dictionary
    Args:
        merged (dict): contains the merged rollout information
        critic (tf.keras.Model): Reinforcement learning critic network from agents.py; here for advantages bootstrapping
        
    Return:
        The dict with the rollout information has been expanded by returns and advantages
    """
    # accessing the last feature sets and messsages for bootstrapping
    last_features_a1 = merged["agent_1"]["features"][:, -1]
    last_features_a2 = merged["agent_2"]["features"][:, -1]
    last_msg_a1 = merged["agent_2"]["output_messages"][:, -1] 
    last_msg_a2 = merged["agent_1"]["output_messages"][:, -1] 
    last_prev_state_critic_a1 = (merged["agent_1"]["prev_state_critic_h"][:, -1], merged["agent_1"]["prev_state_critic_c"][:, -1])
    last_prev_state_critic_a2 = (merged["agent_2"]["prev_state_critic_h"][:, -1], merged["agent_2"]["prev_state_critic_c"][:, -1])
    # creating the bootstrapping values 
    last_val_a1, _ = critic(last_features_a1, last_msg_a1, last_prev_state_critic_a1)
    last_val_a2, _ = critic(last_features_a2, last_msg_a2, last_prev_state_critic_a2)

    all_vals_a1 = tf.concat([merged["agent_1"]["values"], last_val_a1[:, None]], axis=1)
    all_vals_a2 = tf.concat([merged["agent_2"]["values"], last_val_a2[:, None]], axis=1)
    
    returns_a1 , advantages_a1 = helpers.compute_gae(merged["agent_1"]["joint_rewards"],all_vals_a1)
    returns_a2 , advantages_a2 = helpers.compute_gae(merged["agent_2"]["joint_rewards"], all_vals_a2)
    
    merged["agent_1"]["returns"] = returns_a1           # shape [batch_size,]
    merged["agent_1"]["advantages"] = advantages_a1     # shape [batch_size,]
    merged["agent_2"]["returns"] = returns_a2           # shape [batch_size,]
    merged["agent_2"]["advantages"] = advantages_a2     # shape [batch_size,]

    return merged

def rollouts_to_dataset(merged, buffer_size, batch_size):    
    """ flattens the merged rollouts and turns them into a tf.dataset
    Args:
        merged (dict): A dict that contains all PPO information from the rollout relevant for the training step
        buffer_size (int): Buffer size for shuffling a tf.dataset
        batch_size (int): Size of the batch produced
    
    Return:
        A tf.dataset that contains all PPO information from the rollout relevant for the training step"""

    def flatten(x):
        """manual flattening for easier dataset slicing"""
        x_shape = tf.shape(x)
        if tf.rank(x) == 2:
            return tf.reshape(x, [x_shape[0] * x_shape[1]])  # flatten completely
        else:
            return tf.reshape(x, tf.concat([[x_shape[0] * x_shape[1]], x_shape[2:]], axis=0))


    a1_flat = {k: flatten(v) for k, v in merged["agent_1"].items()}
    a2_flat = {k: flatten(v) for k, v in merged["agent_2"].items()}


    dataset = tf.data.Dataset.from_tensor_slices({
        "agent_1": a1_flat,                         # each key now has (batch_size*(num_steps*k)) as first dimension
        "agent_2": a2_flat,
    })

    dataset = dataset.shuffle(buffer_size).batch(batch_size)
    return dataset


def evaluate_policy_reward(agent, critic,
                           num_steps, num_envs,
                           feature_dim, num_same, num_diff1, num_diff2,
                           which, dummy, trivial):
    """ Evalutes the policy by calculating the average rewards of a small sample of rollouts
    Args:
        agent (tf.keras.Model): A reinforcement learning actor network from agents.py
        critic (tf.keras.Model): A reinforcement learning critic network from agents.py
        num_steps (int): Number of steps per game instance 
        num_envs (int): Number of environments collected from in paralell
        feature_dim (int): Length of feature vectors
        num_same (int): Number of objects that are shared between agents
        num_diff1 (int): Number of objects that are only perceived by agent 1
        num_diff2 (int): Number of objects that are only perceived by agent 2
        which (str): String that details whether the train, test, or validation portion of the input dataset is used
        dummy (bool): Flag whether the dataset used is the dummy data or the preprocessed dataset containing image features from mscoco (processed through imagenet)
        trivial (bool): Flag for trivial dataset that contains the same feature vectors and target across the whole training (for debugging only)

    Returns: Average reward across all rollouts as a float.
    """

    if dummy:
        dataset = generate_dummy_ppo_dataset(
            num_same, num_diff1, num_diff2,
            shuffle_buffer_size=1,
            prefetch_buffer_size=1,
            batch_size=1,
            which=which,
            feature_dim=feature_dim
        )
    elif trivial:
        dataset = generate_trivial_ppo_dataset(feature_dim=16, batch_size=1)
    else: 
        dataset = generate_ppo_dataset(
            num_same, num_diff1, num_diff2,
            shuffle_buffer_size=1,
            prefetch_buffer_size=1,
            batch_size=1,
            which=which
        )

    rewards = []

    for (features_a1, targets_a1), (features_a2, targets_a2) in dataset.take(num_envs):
        rollout = do_n_rollout_steps(agent, critic,
                                      features_a1, targets_a1,
                                      features_a2, targets_a2,
                                      helpers.target_match_ratio,
                                      num_steps)


        r1 = tf.reduce_mean(rollout["agent_1"]["joint_rewards"])
        r2 = tf.reduce_mean(rollout["agent_2"]["joint_rewards"])
        rewards.append(0.5 * (r1 + r2)) 

    return float(np.mean(rewards))


def check_nan(x, desc):
    tf.print(desc, tf.math.reduce_any(tf.math.is_nan(x)))

@tf.function
def train_step(rollout_data, 
                agent, critic, optimizer_agent, optimizer_critic, 
                clip_epsilon, entropy_coef_img, entropy_coef_msg, vocab_size):
    """train step for PPO training between two agents in a bidiriectional multistep referential game
     Args:
        rollout_data (tf.dataset): A tf.dataset that contains all PPO information from the rollout relevant for the training step
        agent (tf.keras.Model):  A reinforcement learning actor network from agents.py
        critic (tf.keras.Model): A reinforcement learning critic network from agents.py
        optimizer_agent, optimizer_critic (tf.keras.optimizers): Optimizers that update the parameters of the agent (actor) and critic networks
        clip_epsilon (float): a hyperparameter to constrain the policy update
        entropy_coef_img (float): hyperparameter to constrain entropy bonus for the image entropy
        entropy_coef_msg (float): hyperparameter to constrain entropy bonus on for the msg entropy
        vocab_size (int):  Size of the discrete communication vocabulary

    Return:
        actor_loss, critic_loss
    """

    with tf.GradientTape(persistent=True) as tape:
        probs_img, probs_msg, _ = agent(rollout_data["features"], rollout_data["input_messages"],
                                             (rollout_data["prev_state_actor_h"], rollout_data["prev_state_actor_c"]))
        vals, _ = critic(rollout_data["features"], rollout_data["input_messages"],
                                             (rollout_data["prev_state_critic_h"], rollout_data["prev_state_critic_c"]))
                             
        #debug
        #probs_img = probs_img*0.9
        img_dist = tfp.distributions.Bernoulli(probs=probs_img)
        img_logps =img_dist.log_prob(rollout_data["preds"])

        msg_dist = tfp.distributions.Categorical(probs=probs_msg) 
        msg_logps = msg_dist.log_prob(rollout_data["output_messages"])


        joint_logps = tf.reduce_sum(img_logps, axis=-1)  + tf.reduce_sum(msg_logps, axis=-1)     

        ratios = tf.exp(joint_logps - rollout_data["joint_logps"])

        # normalizing advantages
        advantages = rollout_data["advantages"]
        #advantages = (advantages - tf.reduce_mean(advantages)) / (tf.math.reduce_std(advantages) + 1e-8)

        unclipped = ratios * advantages
        clipped = tf.clip_by_value(ratios, 1 - clip_epsilon, 1 + clip_epsilon) * advantages

        # get entropy 
        img_entropy = tf.reduce_mean(img_dist.entropy())
        msg_entropy =  tf.reduce_mean(msg_dist.entropy())
        # normalize entropy 
        img_entropy = img_entropy / tf.math.log(2.0)
        msg_entropy = msg_entropy / tf.math.log(tf.cast(vocab_size, tf.float32))

        actor_loss = -tf.reduce_mean(tf.minimum(unclipped, clipped)) - (entropy_coef_img * img_entropy) - (entropy_coef_msg * msg_entropy)
        critic_loss = tf.reduce_mean(tf.square(rollout_data["returns"] - vals))
        #check_nan(actor_loss, "Actor loss NaN:")
        #check_nan(critic_loss, "Critic loss NaN:")
    # Compute gradients
    agent_grads = tape.gradient(actor_loss, agent.trainable_variables)
    critic_grads = tape.gradient(critic_loss, critic.trainable_variables)

    optimizer_agent.apply_gradients(zip(agent_grads, agent.trainable_variables))
    optimizer_critic.apply_gradients(zip(critic_grads, critic.trainable_variables))
    kl_estimate = joint_logps - rollout_data["joint_logps"]
    del tape

    return actor_loss, critic_loss, kl_estimate


def train(args, run_dir):
    """
    Args: 
        args (parser object): contains all hyperparameters for     
                                -   the environment/dataset (num_same, num_diff1, num_diff2, feature_dim, dummy),  
                                -   training (num_epochs, updates_per_epoch, num_steps, num_envs, batch_size, which_dataset), 
                                -   PPO specific (actor_lr, critic_lr, clip_epsilon, entropy_coef), 
                                -   networks (vocab_size, msg_len), 
                                -   and others (save_every)
        run_dir (str): path to the directory associated with the current run
    
    Returns:
        A dictionary with raw per step actor and critic losses, mean actor and critic losses per epoch, as well as train and evaluatión rewards.
        
"""

    shuffle_buffer_size = 512
    prefetch_buffer_size = 512

    if args.dummy:
        args.feature_dim = 16

    if args.trivial:
        args.feature_dim = 16



    agent, critic, optimizer_agent, optimizer_crit = initialize_agents(actor_lr=args.actor_lr, critic_lr=args.critic_lr, 
                                                                       feature_dim=args.feature_dim, embed_dim=args.embed_dim, lstm_units=args.lstm_units,
                                                                       vocab_size=args.vocab_size, msg_len=args.msg_len, which_agent=args.which_agent)
    

    train_rewards = []
    last_step_rewards = []
    train_accuracies = []
    exact_match_accuracies = []

    # eval_rewards = []
    mean_actor_losses_epoch = []
    mean_critic_losses_epoch = []
    raw_rewards = []
    all_preds = []
    all_targets = []
    all_messages = []

    buffer_rewards = []
    buffer_actor_losses = []
    buffer_critic_losses = []
    buffer_messages = []
    buffer_preds = []
    buffer_targets = []

    i = 0
    # TensorArrays to store losses
    actor_losses = tf.TensorArray(tf.float32, size=0, dynamic_size=True)
    critic_losses = tf.TensorArray(tf.float32, size=0, dynamic_size=True)

    # initialize dataset
    if args.dummy:
        print("WARNING, dummy mode for testing only")
        dataset = generate_dummy_ppo_dataset(num_same=args.num_same, num_diff1=args.num_diff1, num_diff2=args.num_diff2,
                                             shuffle_buffer_size=shuffle_buffer_size, prefetch_buffer_size=prefetch_buffer_size,
                                             batch_size=args.batch_size, which=args.which_dataset, feature_dim=args.feature_dim)
    elif args.trivial:
        print("WARNING, trivial mode for testing only")
        dataset = generate_trivial_ppo_dataset(feature_dim=16, batch_size=1)

    else:
        dataset = generate_ppo_dataset(num_same=args.num_same, num_diff1=args.num_diff1, num_diff2=args.num_diff2,
                                       shuffle_buffer_size=shuffle_buffer_size, prefetch_buffer_size=prefetch_buffer_size,
                                       batch_size=args.num_envs, which=args.which_dataset)
    tqdm_iter = tqdm(range(args.num_epochs), desc="Training Progress")
    for epoch in tqdm_iter:
        # entropy bonus anneals down; might need to be adjusted depending on final experiments
        ent_msg = helpers.linear_anneal(
            epoch,
            start_epoch=0.2 * args.num_epochs,   
            end_epoch=0.8 * args.num_epochs,     
            start_val=1e-3,
            end_val=1e-4,
        )
        ent_img = helpers.linear_anneal(
            epoch,
            start_epoch=0.2 * args.num_epochs,
            end_epoch=0.8 * args.num_epochs,
            start_val=1e-4,
            end_val=0.0,
        )


        k_rollouts = math.ceil(args.ppo_buffer_size / (args.num_envs*args.num_steps))  # calculate how many rollouts we need to collect to fill the PPO buffer
        k_rollouts = do_k_rollouts(dataset,
                                   agent, critic,
                                   reward_function=helpers.target_match_ratio,
                                   num_steps=args.num_steps, k_rollouts=k_rollouts)
        
        merged_rollouts = merge_rollouts(k_rollouts)
        
        # logging of rollout data
        mean_reward = helpers.calculate_train_reward(merged_rollouts)
        train_rewards.append(mean_reward)
        lsr = tf.reduce_mean(merged_rollouts["agent_1"]["joint_rewards"][:, -1])
        last_step_rewards.append(lsr)  # reward of the last step of the rollout, only agent 1 since both agents get the same joint reward

        train_accuracy = helpers.calculate_mean_label_accuracy(merged_rollouts)
        train_accuracies.append(train_accuracy)

        exact_match_accuracy = helpers.calculate_exact_match_accuracy(merged_rollouts)
        exact_match_accuracies.append(exact_match_accuracy)

        combined = helpers.combine_dicts(merged_rollouts["agent_1"], merged_rollouts["agent_2"])

        raw_rewards.append(combined["joint_rewards"])
        all_preds.append(combined["preds"])
        all_targets.append(combined["targets"])
        all_messages.append(combined["input_messages"])

        buffer_rewards.append(combined["joint_rewards"])
        buffer_messages.append(combined["input_messages"])
        buffer_preds.append(combined["preds"])
        buffer_targets.append(combined["targets"])

        # adding advantages and returns to rollout dict
        merged_rollouts = prepare_ppo_information(merged_rollouts, critic)
        #fix state data in rollouts
        merged_rollouts['agent_1']['prev_state_actor_h'] = helpers.fix_state_timestep(merged_rollouts['agent_1']['prev_state_actor_h'])
        merged_rollouts['agent_1']['prev_state_actor_c'] = helpers.fix_state_timestep(merged_rollouts['agent_1']['prev_state_actor_c'])
        merged_rollouts['agent_2']['prev_state_actor_h'] = helpers.fix_state_timestep(merged_rollouts['agent_2']['prev_state_actor_h'])
        merged_rollouts['agent_2']['prev_state_actor_c'] = helpers.fix_state_timestep(merged_rollouts['agent_2']['prev_state_actor_c'])
        rollout_dataset = rollouts_to_dataset(merged_rollouts, buffer_size=shuffle_buffer_size, batch_size=args.batch_size)

        epoch_actor_losses = []
        epoch_critic_losses = []
        for sub_epoch in tf.range(args.updates_per_epoch):
            kl_agg = []
            for batch in rollout_dataset:
                i = i+1

                combined_batch = helpers.combine_dicts(batch["agent_1"], batch["agent_2"])

                actor_loss, critic_loss, kl = train_step(combined_batch, agent, critic,
                                                        optimizer_agent, optimizer_crit,
                                                        clip_epsilon=args.clip_epsilon, 
                                                        entropy_coef_img=ent_img, entropy_coef_msg=ent_msg,
                                                        vocab_size=args.vocab_size)
                # Write into TensorArrays
                actor_losses = actor_losses.write(i, actor_loss)
                critic_losses = critic_losses.write(i, critic_loss)

                epoch_actor_losses.append(actor_loss)
                epoch_critic_losses.append(critic_loss)
                buffer_actor_losses.append(actor_loss)
                buffer_critic_losses.append(critic_loss)
                kl_agg.append(tf.reduce_mean(kl))
            kl_estimate = tf.reduce_mean(kl_agg)
            #Early stopping of PPO cycle if KL divergence exceeds intended maximum
            if kl_estimate.numpy() > args.ppo_kl_early_stopping_threshold:
                print(f'KL estimate exceeded proposed maximum kl divergence, broke PPO update in sub_epoch {sub_epoch} out of {args.updates_per_epoch}')
                break
        mean_actor_loss_epoch = tf.reduce_mean(epoch_actor_losses)
        mean_critic_loss_epoch = tf.reduce_mean(epoch_critic_losses)
        
        mean_actor_losses_epoch.append(mean_actor_loss_epoch)
        mean_critic_losses_epoch.append(mean_critic_loss_epoch)

        # eval_reward = evaluate_policy_reward(agent, critic,
        #                 num_steps=args.num_steps, num_envs=args.num_envs,
        #                 feature_dim=args.feature_dim, 
        #                 num_same=args.num_same, num_diff1=args.num_diff1, num_diff2=args.num_diff2,
        #                 which=args.which_dataset, dummy=args.dummy, trivial=args.trivial)

        # eval_rewards.append(eval_reward)

        buffer_data={
        "rewards": buffer_rewards,
        "actor_losses": buffer_actor_losses,
        "critic_losses": buffer_critic_losses,
        "messages": buffer_messages,
        "preds": buffer_preds,
        "targets": buffer_targets,
        }

        # if no saving of intermediary result, then set buffer_data=None
        helpers.save_checkpoints(run_dir, epoch, agent, critic, num_epochs=args.num_epochs, save_every=args.save_every, buffer_data=None)
        # Clear buffers after saving to prevent memory growth
        if epoch % args.save_every == 0 and epoch != 0:
            buffer_rewards.clear()
            buffer_actor_losses.clear()
            buffer_critic_losses.clear()
            buffer_messages.clear()
            buffer_preds.clear()
            buffer_targets.clear()
        # ("eval reward in current epoch: ", eval_reward)
        #set tqdm desc
        tqdm_iter.set_description(f"LS-Reward: {lsr.numpy()}, KL[last]:{kl_estimate.numpy()}")
    # Stack TensorArrays to tensors
    actor_losses = actor_losses.stack()
    critic_losses = critic_losses.stack()

    return {
    "raw_actor_losses": actor_losses,
    "raw_critic_losses": critic_losses,
    "mean_actor_losses_per_epoch": mean_actor_losses_epoch,
    "mean_critic_losses_per_epoch": mean_critic_losses_epoch,
    "train_accuracies": train_accuracies,
    "exact_match_accuracies": exact_match_accuracies,
    "train_rewards": train_rewards,
    "last_step_rewards": last_step_rewards,
    "raw_rewards": raw_rewards,
    "preds": all_preds,
    "targets": all_targets,
    "messages": all_messages,
    }




if __name__ == "__main__":


    args = get_args()
    # args = load_config("/home/vanfra/recovered files/bidirectional_signallling_game/config.json")

    run_dir = helpers.setup_run_dir(args)

    training_results = train(args, run_dir)
        
    helpers.save_step_metrics(training_results, run_dir)
    helpers.save_epoch_metrics(training_results, run_dir)
    helpers.save_raw_data(training_results, run_dir)

    helpers.visualize_training_curves(  training_rewards = training_results["train_rewards"],
                                        last_step_rewards = training_results["last_step_rewards"],
                                        training_accuracies = training_results["train_accuracies"],
                                        match_accuracies = training_results["exact_match_accuracies"],
                                        actor_losses = training_results["mean_actor_losses_per_epoch"], 
                                        critic_losses = training_results["mean_critic_losses_per_epoch"], 
                                        save_path=f"{run_dir}/plots/training_curves.png")
